# -*- coding: utf-8 -*-
"""anomalydino-demo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VJUVK2nHCkCDLAjrlzXaX_N9EQr2EyjA
"""

!git clone --branch feat/add-patch https://github.com/ysk35/dino-ano1.git

# Commented out IPython magic to ensure Python compatibility.
# %cd dino-ano1

# Commented out IPython magic to ensure Python compatibility.
# %ls

!pip install "numpy<2.0" faiss-cpu tifffile --no-cache

import faiss, numpy as np, tifffile
print(f"NumPy: {np.__version__}")     # 1.26.x
print(f"FAISS: {faiss.__version__}")  # 1.7.x or 1.8.x
print("✅ 全て正常動作")

from google.colab import drive
drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
# %cd dino-ano1

!cp "/content/drive/MyDrive/m2/data/mvtec_anomaly_detection.tar.xz" .

# Commented out IPython magic to ensure Python compatibility.
# %mkdir data

# Commented out IPython magic to ensure Python compatibility.
# %cd data
# %mkdir mvtec_anomaly_detection
# %cd ..

!tar -xf mvtec_anomaly_detection.tar.xz -C data/mvtec_anomaly_detection
!ls data/mvtec_anomaly_detection

!python run_anomalydino.py \
    --dataset MVTec \
    --data_root data/mvtec_anomaly_detection \
    --shots 1 \
    --num_seeds 3 \
    --stage1_threshold 0.16 \
    --stage2_threshold 0.12 \
    --preprocess informed \
    --faiss_on_cpu

!python analyze_fn.py results_MVTec/dinov2_vits14_448/1-shot_preprocess=informed/detailed_scores_bottle_1shot.json \
  --stage1_threshold 0.16 \
  --stage2_threshold 0.12

!python visualize_scores.py results_MVTec/dinov2_vits14_448/1-shot_preprocess=informed/detailed_scores_bottle_1shot.json \
 --output score_analysis.png

!python analyze_fn.py results_MVTec/dinov2_vits14_448/1-shot_preprocess=informed/detailed_scores_cable_1shot.json

  # 2. capsuleのFN分析（Seed依存性が大きい）
!python analyze_fn.py results_MVTec/dinov2_vits14_448/1-shot_preprocess=informed/detailed_scores_capsule_1shot.json

  # 3. screwのFN分析
!python analyze_fn.py results_MVTec/dinov2_vits14_448/1-shot_preprocess=informed/detailed_scores_screw_1shot.json

import json

with open('results_MVTec/dinov2_vits14_448/1-shot_preprocess=informed/detailed_scores_cable_1shot.json') as f:
  data = json.load(f)
print('=== cable_swap サンプルのスコア ===')
for key, val in sorted(data.items()):
    if 'cable_swap' in key:
          print(f"{key}:")
          print(f"  patch: {val['patch_score']:.4f}, stats: {val['stats_score']:.4f}")
          print(f"  判定: {val['is_anomaly']}, 方法: {val['detection_method']}")
          print(f"  gt_label: {val['gt_label']}")
          print()

import json
import numpy as np

# 結果ディレクトリを指定
results_dir = "results_MVTec/dinov2_vits14_448/1-shot_preprocess=informed"
num_seeds = 3

# データ読み込み
all_metrics = {}
for seed in range(num_seeds):
    try:
        with open(f"{results_dir}/metrics_seed={seed}.json") as f:
            all_metrics[seed] = json.load(f)
        print(f"✅ Seed {seed}: 読み込み成功")
    except:
        print(f"⚠️  Seed {seed}: ファイルなし")

if not all_metrics:
    print("❌ データが見つかりません")
else:
    # オブジェクト一覧
    objects = list(all_metrics[0].keys())

    print("\n" + "="*80)
    print("{:<15} {:<22} {:<22}".format('Object', 'AUROC', 'F1'))
    print("="*80)

    all_auroc = []
    all_f1 = []

    for obj in sorted(objects):
        auroc_list = []
        f1_list = []

        for s in all_metrics.keys():
            if obj in all_metrics[s]:
                data = all_metrics[s][obj]
                # 辞書かどうかチェック
                if isinstance(data, dict):
                    if 'classification_AUROC' in data:
                        auroc_list.append(data['classification_AUROC'])
                    if 'classification_F1' in data:
                        f1_list.append(data['classification_F1'])

        if auroc_list and f1_list:
            auroc_mean, auroc_std = np.mean(auroc_list), np.std(auroc_list)
            f1_mean, f1_std = np.mean(f1_list), np.std(f1_list)

            all_auroc.append(auroc_mean)
            all_f1.append(f1_mean)

            print("{:<15} {:.4f}±{:.4f}     {:.4f}±{:.4f}".format(obj, auroc_mean, auroc_std, f1_mean,
f1_std))
        else:
            print("{:<15} ⚠️  データ不正".format(obj))

    print("="*80)
    if all_auroc and all_f1:
        print("{:<15} {:.4f}±{:.4f}     {:.4f}±{:.4f}".format('Average', np.mean(all_auroc),
np.std(all_auroc), np.mean(all_f1), np.std(all_f1)))
    print("="*80)

    # Seed依存性が高いオブジェクト
    print("\n🔍 Seed依存性が高い（不安定）Top 3:")
    variability = []
    for obj in objects:
        auroc_list = []
        for s in all_metrics.keys():
            if obj in all_metrics[s]:
                data = all_metrics[s][obj]
                if isinstance(data, dict) and 'classification_AUROC' in data:
                    auroc_list.append(data['classification_AUROC'])

        if len(auroc_list) >= 2:
            variability.append((obj, np.std(auroc_list), auroc_list))

    for obj, std, values in sorted(variability, key=lambda x: x[1], reverse=True)[:3]:
        seed_str = ", ".join(["S{}={:.3f}".format(i, v) for i, v in enumerate(values)])
        print("  {:<15} std={:.4f}  ({})".format(obj, std, seed_str))

import json

# 全オブジェクトでStage2の貢献度をチェック
objects = ['bottle', 'cable', 'capsule', 'carpet', 'grid', 'hazelnut',
            'leather', 'metal_nut', 'pill', 'screw', 'tile',
            'toothbrush', 'transistor', 'wood', 'zipper']

results_dir = "results_MVTec/dinov2_vits14_448/1-shot_preprocess=informed"

print("="*80)
print("{:<15} {:<12} {:<12} {:<10}".format('Object', 'Stage1検知', 'Stage2検知', 'Stage2率'))
print("="*80)

total_stage1 = 0
total_stage2 = 0

for obj in objects:
    try:
        with open("{}/detailed_scores_{}_1shot.json".format(results_dir, obj)) as f:
            data = json.load(f)

        stage1 = sum(1 for v in data.values() if v['detection_method'] == 'patch_based')
        stage2 = sum(1 for v in data.values() if v['detection_method'] == 'statistics_based')

        total_stage1 += stage1
        total_stage2 += stage2

        total = stage1 + stage2
        stage2_ratio = (stage2 / total * 100) if total > 0 else 0

        print("{:<15} {:<12} {:<12} {:>6.1f}%".format(obj, stage1, stage2, stage2_ratio))
    except:
        print("{:<15} ファイルなし".format(obj))

print("="*80)
total = total_stage1 + total_stage2
if total > 0:
    print("{:<15} {:<12} {:<12} {:>6.1f}%".format('Total', total_stage1, total_stage2,
total_stage2/total*100))
else:
    print("{:<15} {:<12} {:<12} {}".format('Total', total_stage1, total_stage2, 'N/A'))
print("="*80)

if total_stage2 == 0:
    print("\n⚠️  Stage2での検知が0件です！")
    print("   → Stage2は実装されているが、全く機能していません")
    print("   → stats_scoreが全て閾値0.12を下回っている可能性大")
else:
    print("\n✅ Stage2が機能しています（{}件 / {}件 = {:.1f}%）".format(total_stage2, total,
total_stage2/total*100))

import json

objects = ['bottle', 'cable', 'capsule', 'carpet', 'grid', 'hazelnut',
            'leather', 'metal_nut', 'pill', 'screw', 'tile',
            'toothbrush', 'transistor', 'wood', 'zipper']

results_dir = "results_MVTec/dinov2_vits14_448/1-shot_preprocess=informed"

print("="*100)
print("{:<15} {:<10} {:<10} {:<12} {:<12} {:<10}".format(
    'Object', 'Stage1', 'Stage2-TP', 'Stage2-FP', 'Stage2合計', '真の寄与率'))
print("="*100)

total_stage1 = 0
total_stage2_tp = 0  # True Positive（異常を正しく検知）
total_stage2_fp = 0  # False Positive（正常を誤検知）

for obj in objects:
    try:
        with open("{}/detailed_scores_{}_1shot.json".format(results_dir, obj)) as f:
            data = json.load(f)

        stage1 = sum(1 for v in data.values() if v['detection_method'] == 'patch_based')

        # Stage2を正しく分類
        stage2_tp = sum(1 for v in data.values()
                        if v['detection_method'] == 'statistics_based'
                        and v['gt_label'] == True)  # 異常を正しく検知

        stage2_fp = sum(1 for v in data.values()
                        if v['detection_method'] == 'statistics_based'
                        and v['gt_label'] == False)  # 正常を誤検知

        total_stage1 += stage1
        total_stage2_tp += stage2_tp
        total_stage2_fp += stage2_fp

        stage2_total = stage2_tp + stage2_fp
        total_anomaly = sum(1 for v in data.values() if v['gt_label'] == True)
        contribution = (stage2_tp / total_anomaly * 100) if total_anomaly > 0 else 0

        print("{:<15} {:<10} {:<10} {:<12} {:<12} {:>6.1f}%".format(
            obj, stage1, stage2_tp, stage2_fp, stage2_total, contribution))
    except:
        print("{:<15} ファイルなし".format(obj))

print("="*100)
total_anomaly_all = total_stage1 + total_stage2_tp
contribution_overall = (total_stage2_tp / total_anomaly_all * 100) if total_anomaly_all > 0 else 0

print("{:<15} {:<10} {:<10} {:<12} {:<12} {:>6.1f}%".format(
    'Total', total_stage1, total_stage2_tp, total_stage2_fp,
    total_stage2_tp + total_stage2_fp, contribution_overall))
print("="*100)

print("\n📊 サマリー:")
print("  Stage1で検知した異常:     {}件".format(total_stage1))
print("  Stage2で救済した異常(TP): {}件 ← 真の寄与".format(total_stage2_tp))
print("  Stage2が誤検知した(FP):   {}件 ← マイナス効果".format(total_stage2_fp))
print("  Stage2の真の寄与率:       {:.2f}%".format(contribution_overall))

if total_stage2_tp == 0:
    print("\n⚠️  Stage2は異常を1件も救済していません（完全に無機能）")
elif total_stage2_fp > total_stage2_tp:
    print("\n⚠️  Stage2のFPがTPより多い（悪化させています）")

# ==========================================
# FN/FP詳細分析（Colabセル用）
# ==========================================

import json
import numpy as np

results_dir = "results_MVTec/dinov2_vits14_448/1-shot_preprocess=informed"

objects = ['bottle', 'cable', 'capsule', 'carpet', 'grid', 'hazelnut',
            'leather', 'metal_nut', 'pill', 'screw', 'tile',
            'toothbrush', 'transistor', 'wood', 'zipper']

# 閾値（Stage1のみ使用）
threshold = 0.16

print("="*100)
print("現状の間違い分析（Stage1のみ、閾値=0.16）")
print("="*100)

all_fn = []  # False Negative (見逃し)
all_fp = []  # False Positive (誤検知)

for obj in objects:
    try:
        with open("{}/detailed_scores_{}_1shot.json".format(results_dir, obj)) as f:
            data = json.load(f)

        fn_samples = []
        fp_samples = []

        for key, val in data.items():
            patch_score = val['patch_score']
            gt_label = val['gt_label']

            # FN: 異常だが検知できず (patch_score <= threshold)
            if gt_label == True and patch_score <= threshold:
                fn_samples.append((key, patch_score))
                all_fn.append((obj, key, patch_score))

            # FP: 正常だが誤検知 (patch_score > threshold)
            elif gt_label == False and patch_score > threshold:
                fp_samples.append((key, patch_score))
                all_fp.append((obj, key, patch_score))

        if fn_samples or fp_samples:
            print("\n【{}】".format(obj))
            if fn_samples:
                print("  FN (見逃し): {}件".format(len(fn_samples)))
                for key, score in sorted(fn_samples, key=lambda x: x[1])[:3]:
                    print("    - {}: score={:.4f}".format(key, score))
            if fp_samples:
                print("  FP (誤検知): {}件".format(len(fp_samples)))
                for key, score in sorted(fp_samples, key=lambda x: x[1], reverse=True)[:3]:
                    print("    - {}: score={:.4f}".format(key, score))
    except:
        pass

# サマリー
print("\n" + "="*100)
print("総合サマリー")
print("="*100)
print("総FN (見逃し):  {}件".format(len(all_fn)))
print("総FP (誤検知):  {}件".format(len(all_fp)))
print("総エラー:       {}件".format(len(all_fn) + len(all_fp)))

# FNを異常タイプ別に集計
print("\n【FN（見逃し）を異常タイプ別に集計】")
fn_by_type = {}
for obj, key, score in all_fn:
    anomaly_type = key.split('/')[0]
    if anomaly_type not in fn_by_type:
        fn_by_type[anomaly_type] = []
    fn_by_type[anomaly_type].append((obj, key, score))

for anomaly_type, samples in sorted(fn_by_type.items(), key=lambda x: len(x[1]), reverse=True)[:10]:
    avg_score = np.mean([s[2] for s in samples])
    print("  {:<20} {}件 (平均score={:.4f})".format(anomaly_type, len(samples), avg_score))

# FNのスコア分布
if all_fn:
    fn_scores = [s[2] for s in all_fn]
    print("\n【FN（見逃し）のスコア分布】")
    print("  平均: {:.4f}".format(np.mean(fn_scores)))
    print("  中央値: {:.4f}".format(np.median(fn_scores)))
    print("  最大: {:.4f}".format(np.max(fn_scores)))
    print("  最小: {:.4f}".format(np.min(fn_scores)))
    print("  現在の閾値: 0.16")

# 閾値調整シミュレーション
print("\n" + "="*100)
print("閾値調整シミュレーション")
print("="*100)
print("{:<10} {:<12} {:<12} {:<12} {:<12}".format("閾値", "FN削減", "残りFN", "新FP増加", "総エラー"))
print("-"*60)

current_fn = len(all_fn)
current_fp = len(all_fp)

for new_threshold in [0.10, 0.12, 0.14, 0.16, 0.18, 0.20]:
    new_fn = 0
    new_fp = 0

    for obj in objects:
        try:
            with open("{}/detailed_scores_{}_1shot.json".format(results_dir, obj)) as f:
                data = json.load(f)

            for val in data.values():
                patch_score = val['patch_score']
                gt_label = val['gt_label']

                if gt_label == True and patch_score <= new_threshold:
                    new_fn += 1
                elif gt_label == False and patch_score > new_threshold:
                    new_fp += 1
        except:
            pass

    fn_reduction = current_fn - new_fn
    fp_increase = new_fp - current_fp
    total_error = new_fn + new_fp

    marker = " ← 現在" if new_threshold == 0.16 else ""
    print("{:<10.2f} {:<12} {:<12} {:<12} {:<12}{}".format(
        new_threshold, fn_reduction, new_fn, fp_increase, total_error, marker))

print("="*100)

# 最悪のケースTop 10
print("\n【最も見逃しが多い異常タイプ Top 10】")
for i, (anomaly_type, samples) in enumerate(sorted(fn_by_type.items(),
                                                      key=lambda x: len(x[1]),
                                                      reverse=True)[:10], 1):
    sample_list = ", ".join(["{}/{}".format(s[0], s[1].split('/')[1][:15]) for s in samples[:3]])
    print("{}. {:<20} {}件 - 例: {}".format(i, anomaly_type, len(samples), sample_list))

import json
import numpy as np

results_dir = "results_MVTec/dinov2_vits14_448/1-shot_preprocess=informed"
problem_objects = ['cable', 'transistor', 'hazelnut', 'screw']

for obj in problem_objects:
    with open("{}/detailed_scores_{}_1shot.json".format(results_dir, obj)) as f:
        data = json.load(f)

    # 正常サンプルのスコア
    normal_scores = [v['patch_score'] for v in data.values() if v['gt_label'] == False]

    print("\n【{}】正常サンプルのスコア分布".format(obj))
    print("  平均: {:.4f}".format(np.mean(normal_scores)))
    print("  中央値: {:.4f}".format(np.median(normal_scores)))
    print("  最大: {:.4f}".format(np.max(normal_scores)))
    print("  最小: {:.4f}".format(np.min(normal_scores)))
    print("  標準偏差: {:.4f}".format(np.std(normal_scores)))
    print("  閾値0.16超: {}/{}件 ({:.1f}%)".format(
        sum(1 for s in normal_scores if s > 0.16),
        len(normal_scores),
        sum(1 for s in normal_scores if s > 0.16) / len(normal_scores) * 100
    ))

results_dir = "results_MVTec/dinov2_vits14_448/1-shot_preprocess=informed"
problem_objects = ['cable', 'transistor', 'hazelnut', 'screw']

print("="*80)
print("{:<15} {:<12} {:<12} {:<12} {:<15}".format(
    "Object", "正常平均", "異常平均", "差分", "最適閾値推定"))
print("="*80)

for obj in problem_objects:
    with open("{}/detailed_scores_{}_1shot.json".format(results_dir, obj)) as f:
        data = json.load(f)

    normal_scores = [v['patch_score'] for v in data.values() if v['gt_label'] == False]
    anomaly_scores = [v['patch_score'] for v in data.values() if v['gt_label'] == True]

    normal_mean = np.mean(normal_scores)
    anomaly_mean = np.mean(anomaly_scores)
    diff = anomaly_mean - normal_mean

    # 最適閾値の推定（正常の最大値と異常の最小値の中間）
    normal_max = np.max(normal_scores)
    anomaly_min = np.min(anomaly_scores)

    if anomaly_min > normal_max:
        optimal_threshold = (normal_max + anomaly_min) / 2
        separable = "✅ 分離可能"
    else:
        # 重なりがある場合、ROC曲線で最適化が必要
        optimal_threshold = (normal_mean + anomaly_mean) / 2
        separable = "❌ 重なりあり"

    print("{:<15} {:<12.4f} {:<12.4f} {:<12.4f} {:.4f} {}".format(
        obj, normal_mean, anomaly_mean, diff, optimal_threshold, separable))

    print("  正常: 最小={:.4f}, 最大={:.4f}".format(np.min(normal_scores), np.max(normal_scores)))
    print("  異常: 最小={:.4f}, 最大={:.4f}".format(np.min(anomaly_scores), np.max(anomaly_scores)))
    print()

print("="*80)

import json
import numpy as np

results_dir = "results_MVTec/dinov2_vits14_448/1-shot_preprocess=informed"

optimal_thresholds = {
    'cable': 0.3968,
    'transistor': 0.3255,
    'hazelnut': 0.3922,
    'screw': 0.2207,
    'default': 0.16
}

objects = ['bottle', 'cable', 'capsule', 'carpet', 'grid', 'hazelnut',
            'leather', 'metal_nut', 'pill', 'screw', 'tile',
            'toothbrush', 'transistor', 'wood', 'zipper']

print("="*90)
print("{:<15} {:<15} {:<15} {:<15}".format(
    "Object", "F1 (現在0.16)", "F1 (最適閾値)", "改善"))
print("="*90)

f1_scores_current = []
f1_scores_optimal = []

for obj in objects:
    with open("{}/detailed_scores_{}_1shot.json".format(results_dir, obj)) as f:
        data = json.load(f)

    threshold_current = 0.16
    threshold_optimal = optimal_thresholds.get(obj, 0.16)

    # 現在の閾値でのF1
    tp_c = sum(1 for v in data.values() if v['gt_label'] and v['patch_score'] > threshold_current)
    fp_c = sum(1 for v in data.values() if not v['gt_label'] and v['patch_score'] > threshold_current)
    fn_c = sum(1 for v in data.values() if v['gt_label'] and v['patch_score'] <= threshold_current)

    precision_c = tp_c / (tp_c + fp_c) if (tp_c + fp_c) > 0 else 0
    recall_c = tp_c / (tp_c + fn_c) if (tp_c + fn_c) > 0 else 0
    f1_c = 2 * precision_c * recall_c / (precision_c + recall_c) if (precision_c + recall_c) > 0 else 0

    # 最適閾値でのF1
    tp_o = sum(1 for v in data.values() if v['gt_label'] and v['patch_score'] > threshold_optimal)
    fp_o = sum(1 for v in data.values() if not v['gt_label'] and v['patch_score'] > threshold_optimal)
    fn_o = sum(1 for v in data.values() if v['gt_label'] and v['patch_score'] <= threshold_optimal)

    precision_o = tp_o / (tp_o + fp_o) if (tp_o + fp_o) > 0 else 0
    recall_o = tp_o / (tp_o + fn_o) if (tp_o + fn_o) > 0 else 0
    f1_o = 2 * precision_o * recall_o / (precision_o + recall_o) if (precision_o + recall_o) > 0 else 0

    f1_scores_current.append(f1_c)
    f1_scores_optimal.append(f1_o)

    diff = f1_o - f1_c
    marker = "✅ +{:.4f}".format(diff) if diff > 0 else "❌ {:.4f}".format(diff) if diff < 0 else "= 0.0000"

    print("{:<15} {:<15.4f} {:<15.4f} {}".format(obj, f1_c, f1_o, marker))

print("="*90)
avg_f1_current = np.mean(f1_scores_current)
avg_f1_optimal = np.mean(f1_scores_optimal)
improvement = avg_f1_optimal - avg_f1_current

print("{:<15} {:<15.4f} {:<15.4f} {:+.4f}".format(
    "平均", avg_f1_current, avg_f1_optimal, improvement))
print("="*90)

if improvement > 0:
    print("\n✅ オブジェクト別最適閾値で精度が向上します！")
    print("   平均F1スコア: {:.4f} → {:.4f} ({:+.2%})".format(
        avg_f1_current, avg_f1_optimal, improvement/avg_f1_current))
else:
    print("\n❌ オブジェクト別最適閾値では精度が下がります")
    print("   平均F1スコア: {:.4f} → {:.4f} ({:+.2%})".format(
        avg_f1_current, avg_f1_optimal, improvement/avg_f1_current))

print("\n📌 注意:")
print("   - AUROCは閾値を変えても変わりません（スコア分布は同じ）")
print("   - F1スコアは閾値によって変わります")
print("   - この結果は、オブジェクト別閾値の有効性を示します")

# ==========================================
# 詳細ミス分析 - 改善方法発見のため
# ==========================================

import json
import numpy as np
from collections import defaultdict

results_dir = "results_MVTec/dinov2_vits14_448/1-shot_preprocess=informed"
threshold = 0.16

objects = ['bottle', 'cable', 'capsule', 'carpet', 'grid', 'hazelnut',
            'leather', 'metal_nut', 'pill', 'screw', 'tile',
            'toothbrush', 'transistor', 'wood', 'zipper']

# データ収集
all_data = {}
for obj in objects:
    try:
        with open("{}/detailed_scores_{}_1shot.json".format(results_dir, obj)) as f:
            all_data[obj] = json.load(f)
    except:
        pass

print("="*100)
print("詳細ミス分析レポート")
print("="*100)

# ========================================
# 1. 異常タイプ別の失敗分析
# ========================================
print("\n【1. 異常タイプ別の失敗率】")
print("-"*100)

anomaly_type_analysis = defaultdict(lambda: {'total': 0, 'fn': 0, 'tp': 0})

for obj, data in all_data.items():
    for key, val in data.items():
        if val['gt_label']:  # 異常サンプルのみ
            anomaly_type = key.split('/')[0]
            anomaly_type_analysis[anomaly_type]['total'] += 1

            if val['patch_score'] <= threshold:
                anomaly_type_analysis[anomaly_type]['fn'] += 1
            else:
                anomaly_type_analysis[anomaly_type]['tp'] += 1

# 失敗率が高い順にソート
sorted_types = sorted(anomaly_type_analysis.items(),
                      key=lambda x: x[1]['fn']/x[1]['total'] if x[1]['total'] > 0 else 0,
                      reverse=True)

print("{:<25} {:<10} {:<10} {:<15} {:<15}".format(
    "異常タイプ", "総数", "FN", "失敗率", "平均スコア"))
print("-"*100)

for anomaly_type, stats in sorted_types[:20]:
    fn_rate = stats['fn'] / stats['total'] * 100 if stats['total'] > 0 else 0

    # 平均スコアを計算
    scores = []
    for obj, data in all_data.items():
        for key, val in data.items():
            if val['gt_label'] and key.split('/')[0] == anomaly_type:
                scores.append(val['patch_score'])

    avg_score = np.mean(scores) if scores else 0

    marker = "⚠️" if fn_rate > 50 else "✓"
    print("{:<25} {:<10} {:<10} {:<14.1f}% {:<15.4f} {}".format(
        anomaly_type, stats['total'], stats['fn'], fn_rate, avg_score, marker))

# ========================================
# 2. オブジェクト別の問題分析
# ========================================
print("\n" + "="*100)
print("【2. オブジェクト別の問題パターン】")
print("-"*100)

for obj, data in all_data.items():
    normal_scores = [v['patch_score'] for v in data.values() if not v['gt_label']]
    anomaly_scores = [v['patch_score'] for v in data.values() if v['gt_label']]

    if not normal_scores or not anomaly_scores:
        continue

    normal_mean = np.mean(normal_scores)
    anomaly_mean = np.mean(anomaly_scores)
    separation = anomaly_mean - normal_mean

    fn_count = sum(1 for s in anomaly_scores if s <= threshold)
    fp_count = sum(1 for s in normal_scores if s > threshold)

    # 問題のパターンを判定
    problem_pattern = []
    if separation < 0.1:
        problem_pattern.append("分離不良(差={:.3f})".format(separation))
    if normal_mean > 0.25:
        problem_pattern.append("正常が高スコア(μ={:.3f})".format(normal_mean))
    if fp_count > len(normal_scores) * 0.5:
        problem_pattern.append("FP多数({}/{})".format(fp_count, len(normal_scores)))
    if fn_count > 0:
        problem_pattern.append("FN発生({})".format(fn_count))

    if problem_pattern:
        print("\n{}: {}".format(obj, ", ".join(problem_pattern)))
        print("  正常: μ={:.4f}, σ={:.4f}, range=[{:.4f}, {:.4f}]".format(
            normal_mean, np.std(normal_scores), np.min(normal_scores), np.max(normal_scores)))
        print("  異常: μ={:.4f}, σ={:.4f}, range=[{:.4f}, {:.4f}]".format(
            anomaly_mean, np.std(anomaly_scores), np.min(anomaly_scores), np.max(anomaly_scores)))

# ========================================
# 3. スコア分布の問題点
# ========================================
print("\n" + "="*100)
print("【3. スコア分布から見る根本問題】")
print("-"*100)

all_normal_scores = []
all_anomaly_scores = []

for obj, data in all_data.items():
    for val in data.values():
        if val['gt_label']:
            all_anomaly_scores.append(val['patch_score'])
        else:
            all_normal_scores.append(val['patch_score'])

print("\n全体統計:")
print("  正常サンプル (n={}):".format(len(all_normal_scores)))
print("    平均={:.4f}, 中央値={:.4f}, std={:.4f}".format(
    np.mean(all_normal_scores), np.median(all_normal_scores), np.std(all_normal_scores)))
print("    範囲=[{:.4f}, {:.4f}]".format(np.min(all_normal_scores), np.max(all_normal_scores)))

print("\n  異常サンプル (n={}):".format(len(all_anomaly_scores)))
print("    平均={:.4f}, 中央値={:.4f}, std={:.4f}".format(
    np.mean(all_anomaly_scores), np.median(all_anomaly_scores), np.std(all_anomaly_scores)))
print("    範囲=[{:.4f}, {:.4f}]".format(np.min(all_anomaly_scores), np.max(all_anomaly_scores)))

print("\n  分離度: {:.4f} (理想: >0.2)".format(
    np.mean(all_anomaly_scores) - np.mean(all_normal_scores)))

# 重なり率を計算
overlap_min = max(np.min(all_anomaly_scores), np.min(all_normal_scores))
overlap_max = min(np.max(all_anomaly_scores), np.max(all_normal_scores))
overlap_ratio = (overlap_max - overlap_min) / (max(all_anomaly_scores) - min(all_normal_scores))
print("  重なり率: {:.1f}%".format(overlap_ratio * 100))

# ========================================
# 4. 改善方向の提案
# ========================================
print("\n" + "="*100)
print("【4. 改善方向の提案】")
print("="*100)

suggestions = []

# 正常の高スコア問題
high_normal_objects = [obj for obj, data in all_data.items()
                        if np.mean([v['patch_score'] for v in data.values() if not v['gt_label']]) > 0.25]
if len(high_normal_objects) > 3:
    suggestions.append({
        'title': '正常サンプルのスコアが高い ({}/{} objects)'.format(len(high_normal_objects), len(objects)),
        'problem': '1-shotの参照画像では正常のバリエーションをカバーできない',
        'solutions': [
            '→ k-shot (参照画像を増やす): 3-shot, 5-shotで正常の多様性を学習',
            '→ 正常特徴の安定化: メモリバンクの正規化方法を改善',
            '→ オブジェクト別の適応的閾値学習'
        ]
    })

# 分離不良
if overlap_ratio > 0.5:
    suggestions.append({
        'title': '正常と異常の分離が不十分 (重なり率{:.1f}%)'.format(overlap_ratio * 100),
        'problem': 'パッチベース特徴だけでは識別困難',
        'solutions': [
            '→ マルチスケール特徴: 異なる解像度の特徴を組み合わせ',
            '→ 空間的関係の利用: パッチ間の相対位置情報を活用',
            '→ 異常タイプ別の特徴選択: タイプごとに有効な特徴を学習'
        ]
    })

# 特定異常タイプの失敗
high_failure_types = [t for t, s in sorted_types[:5]
                      if s['fn']/s['total'] > 0.3]
if high_failure_types:
    suggestions.append({
        'title': '特定の異常タイプで高失敗率',
        'problem': '微細な異常や構造的異常の検知が困難: {}'.format(', '.join(high_failure_types)),
        'solutions': [
            '→ アンサンブル手法: 複数の特徴抽出器を組み合わせ',
            '→ 注意機構: 異常領域に注目する仕組みを導入',
            '→ 事前学習モデルの変更: DINOv2以外も試す (CLIP, MAE等)'
        ]
    })

for i, sug in enumerate(suggestions, 1):
    print("\n提案{}. {}".format(i, sug['title']))
    print("  問題: {}".format(sug['problem']))
    print("  解決策:")
    for sol in sug['solutions']:
        print("    {}".format(sol))

print("\n" + "="*100)

import json
import numpy as np

results_dir = "results_MVTec/dinov2_vits14_448/1-shot_preprocess=informed"

print("="*80)
print("FPサンプルの特徴分析")
print("="*80)

problem_objects = ['cable', 'transistor']

for obj in problem_objects:
    with open("{}/detailed_scores_{}_1shot.json".format(results_dir, obj)) as f:
        data = json.load(f)

    # FPサンプルのスコア
    fp_samples = [(k, v['patch_score']) for k, v in data.items()
                  if not v['gt_label'] and v['patch_score'] > 0.16]

    # 正常サンプル全体
    normal_scores = [v['patch_score'] for v in data.values() if not v['gt_label']]

    # 異常サンプル全体
    anomaly_scores = [v['patch_score'] for v in data.values() if v['gt_label']]

    print("\n【{}】".format(obj))
    print("  FPサンプル数: {}".format(len(fp_samples)))
    print("  FPスコア範囲: [{:.4f}, {:.4f}]".format(
        min(s for _, s in fp_samples), max(s for _, s in fp_samples)))
    print("  正常全体: μ={:.4f}, range=[{:.4f}, {:.4f}]".format(
        np.mean(normal_scores), min(normal_scores), max(normal_scores)))
    print("  異常全体: μ={:.4f}, range=[{:.4f}, {:.4f}]".format(
        np.mean(anomaly_scores), min(anomaly_scores), max(anomaly_scores)))

    # FPは異常に近いか？
    fp_scores_only = [s for _, s in fp_samples]
    print("\n  FPは異常スコアに近い？")
    print("    FP平均={:.4f} vs 異常平均={:.4f}".format(
        np.mean(fp_scores_only), np.mean(anomaly_scores)))
    print("    差分: {:.4f}".format(np.mean(anomaly_scores) - np.mean(fp_scores_only)))

    # 判定
    if np.mean(fp_scores_only) > np.mean(anomaly_scores) * 0.8:
        print("  → FPは異常に近いスコア（見た目が異常っぽい可能性）")
        print("  → マルチスケールで改善する可能性: 低")
    else:
        print("  → FPは正常と異常の中間（判断が難しい）")
        print("  → マルチスケールで改善する可能性: 中")

print("\n" + "="*80)
print("\n【結論】")
print("  もしFPが「見た目が異常に近い」なら:")
print("    → マルチスケールでは改善しない")
print("    → k-shotで正常の多様性を増やすべき")
print("\n  もしFPが「中間的なスコア」なら:")
print("    → マルチスケールで分離が改善する可能性あり")
print("="*80)

# メトリクスファイルから平均AUROC確認
import json
with open('results_MVTec/dinov2_vits14_448/1-shot_preprocess=informed/metrics_seed=0.json', 'r') as f:
    metrics = json.load(f)
    auroc = metrics['mean_classification_au_roc'] * 100
    print(f"🎯 論文再現結果 - Mean AUROC: {auroc:.2f}%")
    print(f"📊 論文値: 96.6%")
    print(f"✅ 差異: {auroc - 96.6:.1f}%")